<?php

namespace app\modules\dashboard\controllers;

use app\modules\dashboard\models\Cart;
use app\modules\user\models\User;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use Yii;
use yii\web\ForbiddenHttpException;

class BackendController extends Controller {


    public function behaviors() {

        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                        'denyCallback' => function ($rule, $action) {
                            throw new \Exception('Permissions denied');
                        }
                    ],
                ],
            ],
        ];
    }

    public function init() {
        parent::init(); // TODO: Change the autogenerated stub

        $userId = Yii::$app->user->getId();

        switch ($userId) {
            case User::ROLE_ADMIN : return true;
                break;
            case User::ROLE_USER : return true;
                break;
            default : return $this->redirect('/dashboard/login');
        }
    }

    public function actionIndex()
    {
        $cart = new Cart();
        $count = $cart->getTotalFullOrder();

        return $this->render('index',[
            'count' => $count,
        ]);
    }

}
